### ISSUE TITLE
Error line 99 rest-api 

### ISSUE THREAD

**Issue by ulrikkau** [runnane/node-red-contrib-easee#16]
@runnane/node-red-contrib-easee
0.5.6
SyntaxError: Unexpected token '.' (line:99)

**Comment by runnane** [comment]
Hi @ulrikkau 

Do you have more information about this error? What versions of nodered and node are you running? Where do you get this error, in the console or in node-red frontend?
I have checked line 99 in all files, and cannot see any error.

**Comment by I-am-a-node** [comment]
I also had this issue. Every day, long periods, several hours. Did a reset and it was gone until next day. However I had to stop using this node as it made Node-Red crash when there is a WAN or internet connection issue (think is related to the websocket part). Instead of a harmless error msg it killed all other flows by crashing it all. 

I havent had time for any futher re-search or debugging yet. Need to decide if I should spend any more time on this node as it has other limits and disadvantages, .... or setup something else. I'll get back if I'll have some time for it.

**Comment by KIDNORswe** [comment]
Similar issue. Had to reset the streaming node every 24h but still got the Error later the same day.
I live in a remote area with no static connection to the internet. Have to rely on a 4G LTE + that can disconnect a few times a day (on a bad day). This will cause Node-Red to crash because of this node so had to stop using it. I also think it as to do with the websocket or something similar (however only speculation as no proof). Shame I can't use his as its a good idea.

**Comment by KIDNORswe** [comment]
@runnane  Thanks. I hope to get time this weekend running some tests. I'll move my flow with Stream and Rest over to a test container and try to see if I can find out what kicks the negatives. 
I'll try and see if I can find a pattern when it comes to the error codes renewing the token.

**Comment by runnane** [comment]
I have one finding, it seems DNS lookup failures after initial start will crash it.
I will try catching this error. 
`20 Apr 10:19:32 - [error] Error: FetchError: request to https://api.easee.com/api/accounts/login failed, reason: getaddrinfo EAI_AGAIN api.easee.com
    at /data/node_modules/@runnane/node-red-contrib-easee/easee-client/easee-configuration.js:1255:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EaseeConfiguration.node.doLogin (/data/node_modules/@runnane/node-red-contrib-easee/easee-client/easee-configuration.js:1224:26)`

 I will add some better errorhandling around this and release a new version today.

**Comment by I-am-a-node** [comment]
@runnane Tusen takk! Perfect timing catching this error. Excellent job! I appreciate you takin the time to solve it.
I did setup a test container with log yesterday but didn't push or simulate anything. It did crash ones. However I have updated and reset the log. I can see improvements, the repeating "[easee] EaseeConfiguration::doRefreshToken() - No accessToken, exiting" is gone.

**Comment by KIDNORswe** [comment]
Brilliant!  I will start a testing session today. So happy if both the Token and disconnection issue is gone.
Thanks @runnane for solving the issue and making our lives easier now when we can start using your development again.
Go o gla, kexchoklad! :)
